task:
  name: stable
  container:
    image: rust
    cpu: 1
    memory: 1G
  allow_failures: false
  env:
    RUST_BACKTRACE: 1
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock 2> /dev/null || true
  target_cache:
    folder: target
    fingerprint_script: cat Cargo.lock 2> /dev/null || true
  setup_script:
    - rustup component add clippy
  info_script:
    - rustc --version
  check_script:
    - cargo build --no-default-features
    - cargo build --all
    - cargo build --all --features ascii
  test_script:
    - cargo test --all-features --no-fail-fast -- --test-threads=1
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index

task:
  name: MSRV
  container:
    image: rust:1.56
    cpu: 1
    memory: 1G
  allow_failures: false
  env:
    RUST_BACKTRACE: 1
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock 2> /dev/null || true
  target_cache:
    folder: target
    fingerprint_script: cat Cargo.lock 2> /dev/null || true
  info_script:
    - rustc --version
  build_script:
    - cargo build --all-features
  test_script:
    - cargo test --all-features --no-fail-fast -- --test-threads=1
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index

task:
  name: nightly check
  container:
    image: rustlang/rust:nightly
    cpu: 1
    memory: 1G
  allow_failures: false
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock 2> /dev/null || true
  # rustc version is so likely to have changed that build artefacts are not worth caching
  setup_script:
    - cargo install cargo-fuzz
  info_script:
    - rustc --version
  check_script:
    - cargo check --all --benches --all-features
    - cargo fuzz build --all-features
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index
