task:
  name: stable
  container:
    image: rust
    cpu: 1
    memory: 1G
  allow_failures: false
  env:
    RUST_BACKTRACE: 1
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock 2> /dev/null || true
  target_cache:
    folder: target
    fingerprint_script: cat Cargo.lock 2> /dev/null || true
  setup_script:
    - rustup component add clippy
  info_script:
    - rustc --version
  check_script:
    - cargo check --tests --examples --no-default-features
    - cargo check --tests --examples
    - cargo build --tests --examples --features ascii
    - cargo clippy --tests --examples --all-features
  test_script:
    - cargo test --all-features --no-fail-fast -- --test-threads=1
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index

task:
  name: MSRV
  container:
    image: rust:1.56
    cpu: 1
    memory: 1G
  allow_failures: false
  env:
    RUST_BACKTRACE: 1
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock 2> /dev/null || true
  target_cache:
    folder: target
    fingerprint_script: cat Cargo.lock 2> /dev/null || true
  info_script:
    - rustc --version
  build_script:
    # feel free to stop checking tests and examples at MSRV
    - cargo check --no-default-features
    - cargo check --examples --tests
    - cargo build --all-features --examples --tests
  test_script:
    - cargo test --no-fail-fast -- --test-threads=1
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index

task:
  name: nightly check
  container:
    image: rustlang/rust:nightly
    cpu: 1
    memory: 1G
  allow_failures: false
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock 2> /dev/null || true
  # rustc version is so likely to have changed that build artefacts are not worth caching
  setup_script:
    - cargo install cargo-fuzz
  info_script:
    - rustc --version
  check_script:
    - cargo check --benches --no-default-features
    - cargo check --benches
    - cargo check --benches --all-features
    - cargo fuzz build
    # fuzz supports feature selection,
    # but --no-default-features doesn't seem to have any effect.
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index
