[package]
name = "encode_unicode"
keywords = ["unicode","UTF-8","UTF-16"]
description = """
Alternative and extension to the unstable `char.encode_utf8()` and char.encode_utf16()` methods.
Also has UTF-8- and UTF-16-encoded character types.
"""
readme = "README.md"
version = "0.2.0"
license = "MIT/Apache-2.0"
repository = "https://github.com/tormol/encode_unicode"
documentation = "http://tormol.github.io/rustdoc/encode_unicode"
authors = ["Torbjørn Birch Moltu <t.b.moltu@lyse.net>"]

[dependencies]
ascii = {optional=true, version="0.7"}
clippy = {optional=true, version="0.*"}# wildest wildcard crates.io will allow.

[features]
no_std = []
ascii_no_std = ["no_std","ascii/no_std"]
